version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  webui:
    build:
      context: ./docker/webui
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your-secret-key-here
    volumes:
      - webui_data:/app/backend/data
    restart: unless-stopped

  agent:
    build:
      context: ./docker/agent
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./src/data:/app/data
    depends_on:
      - ollama
    environment:
      - AGENT_OLLAMA_BASE_URL=http://ollama:11434
      - AGENT_OLLAMA_MODEL=qwen2:7b-instruct
      - AGENT_DATABASE_URL=sqlite:////app/data/agent.db
      - AGENT_WEB_DESIGN_ENABLED=true
      - AGENT_ENABLE_WEB_SEARCH=true
      - PYTHONPATH=/app/src
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webui
      - agent
    restart: unless-stopped

volumes:
  ollama_data:
  webui_data:

networks:
  default:
    driver: bridge
