# AlertManager 設定ファイル
# Advanced AI Agent アラート管理システム

global:
  smtp_smarthost: "localhost:587"
  smtp_from: "alerts@advanced-agent.local"
  smtp_auth_username: "alerts@advanced-agent.local"
  smtp_auth_password: "password"

# アラートルーティング設定
route:
  group_by: ["alertname", "severity"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "web.hook"
  routes:
    # 重要度別ルーティング
    - match:
        severity: critical
      receiver: "critical-alerts"
      group_wait: 5s
      repeat_interval: 30m

    - match:
        severity: warning
      receiver: "warning-alerts"
      group_wait: 30s
      repeat_interval: 2h

    # コンポーネント別ルーティング
    - match:
        component: gpu
      receiver: "gpu-alerts"

    - match:
        component: inference
      receiver: "inference-alerts"

# アラート受信者設定
receivers:
  # デフォルト受信者
  - name: "web.hook"
    webhook_configs:
      - url: "http://advanced-agent:8000/api/v1/alerts/webhook"
        send_resolved: true

  # 重要アラート受信者
  - name: "critical-alerts"
    email_configs:
      - to: "admin@advanced-agent.local"
        subject: "[CRITICAL] Advanced AI Agent Alert"
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .GroupLabels.severity }}

          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

    webhook_configs:
      - url: "http://advanced-agent:8000/api/v1/alerts/critical"
        send_resolved: true

    slack_configs:
      - api_url: "YOUR_SLACK_WEBHOOK_URL"
        channel: "#alerts-critical"
        title: "Critical Alert: {{ .GroupLabels.alertname }}"
        text: "{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}"

  # 警告アラート受信者
  - name: "warning-alerts"
    email_configs:
      - to: "monitoring@advanced-agent.local"
        subject: "[WARNING] Advanced AI Agent Alert"
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .GroupLabels.severity }}

          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          {{ end }}

    webhook_configs:
      - url: "http://advanced-agent:8000/api/v1/alerts/warning"
        send_resolved: true

  # GPU 専用アラート受信者
  - name: "gpu-alerts"
    webhook_configs:
      - url: "http://advanced-agent:8000/api/v1/alerts/gpu"
        send_resolved: true

    email_configs:
      - to: "gpu-admin@advanced-agent.local"
        subject: "[GPU] Advanced AI Agent GPU Alert"
        body: |
          GPU Alert: {{ .GroupLabels.alertname }}

          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  # 推論専用アラート受信者
  - name: "inference-alerts"
    webhook_configs:
      - url: "http://advanced-agent:8000/api/v1/alerts/inference"
        send_resolved: true

# アラート抑制設定
inhibit_rules:
  # 重要アラートが発生している間は警告アラートを抑制
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]

  # GPU メモリ不足の間は CPU アラートを抑制
  - source_match:
      alertname: "GPUMemoryExhaustion"
    target_match:
      alertname: "HighCPUUsage"
    equal: ["instance"]

# テンプレート設定
templates:
  - "/etc/alertmanager/templates/*.tmpl"
