# Advanced Self-Learning AI Agent System Configuration
# RTX 4050 6GB VRAM 最適化設定

# GPU Configuration
gpu:
  max_vram_gb: 5.0
  quantization_levels: [8, 4, 3]
  temperature_threshold: 80
  memory_reserve_gb: 0.5
  monitoring_interval: 1.0

# CPU Configuration
cpu:
  max_threads: 16
  offload_threshold: 0.8
  hybrid_processing: true

# Memory Configuration
memory:
  system_ram_gb: 32
  swap_limit_gb: 8
  cache_size_mb: 512

# Model Configuration
models:
  primary: "deepseek-r1:7b"
  fallback: "qwen2.5:7b-instruct-q4_k_m"
  emergency: "qwen2:1.5b-instruct-q4_k_m"
  auto_download: true

# Learning Configuration
learning:
  adapter_pool_size: 10
  generation_size: 5
  mutation_rate: 0.1
  crossover_rate: 0.7
  max_training_epochs: 10
  learning_rate: 0.0001

# Memory System Configuration
persistent_memory:
  db_path: "data/agent_memory.db"
  vector_db_path: "data/agent_vectors.db"
  max_short_term_items: 1000
  max_long_term_items: 10000
  importance_threshold: 0.7
  consolidation_interval_hours: 24
  auto_cleanup: true

# Monitoring Configuration
monitoring:
  gpu_monitoring:
    interval_seconds: 1
    metrics: ["utilization", "memory", "temperature"]
    alerts:
      memory_threshold: 0.9
      temperature_threshold: 80
  performance_tracking:
    response_time_target: 2.0
    accuracy_threshold: 0.85
    memory_efficiency_target: 0.8
  logging:
    level: "INFO"
    file_path: "logs/advanced_agent.log"
    max_file_size_mb: 100
    backup_count: 5

# API Configuration
api:
  host: "localhost"
  port: 8000
  max_concurrent_requests: 10
  request_timeout: 30
  openai_compatible: true

# Security Configuration
security:
  enable_encryption: true
  model_integrity_check: true
  data_anonymization: true
