[server]
address = "localhost"
port = 8501
enableCORS = true
enableXsrfProtection = true
enableWebsocketCompression = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[global]
# Streamlit の設定

# 開発モード（新バージョンでは developmentMode は削除）
# developmentMode = false


[theme]
# テーマ設定
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[runner]
# ランナー設定
magicEnabled = true

[logger]
# ログ設定
level = "info"
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s"